language: objective-c
# xcode_project: ActionSheetPicker.xcodeproj # path to your xcodeproj folder
# xcode_scheme: ActionSheetPickerTests
# xcode_sdk: iphonesimulator

notifications:
  email:
    recipients:
      - sky4winder+actionSheetPicker@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]

script:
  - xctool clean build test -workspace Example.xcworkspace -scheme ActionSheetPicker -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=7.1'